language: python
python:
  - "3.6"
script:
  - "./test_main.py"
provider: pypi
user: "martinoj2009"
password:
  secure: "sdFEiqfEiNLEX0Zq7KENNAMA8VRxCPJVJ9RstEE+qdo3u3J1i6yTmye3j9W0TjTFkad5prSOqKcrejszTxmt8GKdSPkYY29qyOQE9I+k9nsxrwM1zcLYC63ww7+HjzDa3s9W0Fe/v+E3Mg3MjJRss64FkLFAihlrj38IX/PanHybomS5VlYRk3uj+7eq68RtXqevtTQfNhVMxOus8izkGphewI7ArMV6U9NJCXgAP7PikVnyVoBgNClBns+LKDd0e3t9Uj3SK2bI61inUvrecRJUpqlPemvffK0wad7CSi0PQ9m+8LJKWB6NjNANJuULYJvbBDCUo51GKPQQnvi2piPdpVzxFfMatVDV28YcAV8D+VPaWU17foKQ5ismbjruwLSezaqTZJzd3lQjk4X4OVKb46BS8jj8TRNNfV0yVCmDPUxSMjNdks9142M8/wAgi3xMwaMpGlFkDpuSfmnmMD999FIJJqISlN4BFbOp9itYpNXDkom6lD2O22EmLZFfxoy7UIH1RA0zq6PxAUv5HyFhSVTUweU0mDcDqKrb0F8NQvQiT+GGejdKbesiXu2GhgJ8F0PTnXj3zMxvp9X9eRtFrJ+1gegtjT6cHRmhXKayEiXDA9M3O8S3nVh6/CeIy/fk6mOgQ+T9YKyRPfJz1To2ByrcHLmqewo3n5np7Oo="